<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4d6e514a-cf80-4ba2-a11c-1d0b7fb18bdd</elementGuidId>
    <imagePath></imagePath>
    <name>button_next</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#next</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'next') and equals(@class,'MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1b3uk2l')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-1b3uk2l</value>
        <webElementGuid>7003cd3b-a9a8-411e-b1c1-e7bb0e211a7d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>next</value>
        <webElementGuid>69886ee2-15db-4338-99fa-fc1a2b3968e8</webElementGuid>
    </webElementProperties>
</WebElementEntity>