<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fc78e726-3208-4cc7-a9b9-eda0c4bc83a3</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.css-ovnx7g</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiStack-root css-ovnx7g')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiStack-root css-ovnx7g</value>
        <webElementGuid>8e4a8847-ef05-49e6-946d-7c08f5ed14fd</webElementGuid>
    </webElementProperties>
</WebElementEntity>