<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b4feeba0-c408-4f1f-b3d3-f0088b587b12</elementGuidId>
    <imagePath></imagePath>
    <name>input_contact_switch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#contact-switch</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'contact-switch') and equals(@class,'PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
        <webElementGuid>5d08f746-4c7f-4513-9b3e-66be7e656d11</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>contact-switch</value>
        <webElementGuid>cdb027ac-205d-4090-bd12-fe399e57596a</webElementGuid>
    </webElementProperties>
</WebElementEntity>